from pymongo import MongoClient

client = MongoClient()
db = client.test

db.WordCount.update({'id':'New York'}, {'city': 'New York', 'data': []},True)
db.WordCount.update({'id':'Los Angeles'}, {'city': 'Los Angeles', 'data': []},True)
db.WordCount.update({'id':'Chicago'}, {'city': 'Chicago', 'data': []},True)
db.WordCount.update({'id':'Dallas'}, {'city': 'Dallas', 'data': []},True)
db.WordCount.update({'id':'Houston'}, {'city': 'Houston', 'data': []},True)
db.WordCount.update({'id':'Philadelphia'}, {'city': 'Philadelphia', 'data': []},True)
db.WordCount.update({'id':'Washington'}, {'city': 'Washington', 'data': []},True)
db.WordCount.update({'id':'Miami'}, {'city': 'Miami', 'data': []},True)
db.WordCount.update({'id':'Atlanta'}, {'city': 'Atlanta', 'data': []},True)
db.WordCount.update({'id':'Boston'}, {'city': 'Boston', 'data': []},True)
db.WordCount.update({'id':'San Francisco'}, {'city': 'San Francisco', 'data': []},True)
db.WordCount.update({'id':'Pheonix'}, {'city': 'Pheonix', 'data':         []},True)
db.WordCount.update({'id':'Detroit'}, {'city': 'Detroit', 'data':         []},True)
db.WordCount.update({'id':'Seattle'}, {'city': 'Seattle', 'data':         []},True)
db.WordCount.update({'id':'Minneapolis'}, {'city': 'Minneapolis', 'data': []},True)
db.WordCount.update({'id':'San Diego'}, {'city': 'San Diego', 'data': []},True)
db.WordCount.update({'id':'Tampa'}, {'city': 'Tampa', 'data': []},True)
db.WordCount.update({'id':'St Louis'}, {'city': 'St Louis', 'data': []},True)
db.WordCount.update({'id':'Baltimore'}, {'city': 'Baltimore', 'data': []},True)
db.WordCount.update({'id':'Denver'}, {'city': 'Denver', 'data': []},True)
db.WordCount.update({'id':'Pittsburgh'}, {'city': 'Pittsburgh', 'data': []},True)
db.WordCount.update({'id':'Charlotte'}, {'city': 'Charlotte', 'data': []},True)
db.WordCount.update({'id':'Portland'}, {'city': 'Portland', 'data': []},True)
db.WordCount.update({'id':'San Antonio'}, {'city': 'San Antonio', 'data': []},True)
db.WordCount.update({'id':'Orlando'}, {'city': 'Orlando', 'data': []},True)
db.WordCount.update({'id':'Sacramento'}, {'city': 'Sacramento', 'data': []},True)
db.WordCount.update({'id':'Cincinnati'}, {'city': 'Cincinnati', 'data': []},True)
db.WordCount.update({'id':'Cleveland'}, {'city': 'Cleveland', 'data': []},True)
db.WordCount.update({'id':'Kansas City'}, {'city': 'Kansas City', 'data': []},True)
db.WordCount.update({'id':'Riverside'}, {'city': 'Riverside', 'data': []},True)
db.WordCount.update({'id':'USA'}, {'city': 'USA', 'data': []},True)
    